# Generated by Django 4.2.16 on 2026-01-01 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_pair', models.CharField(max_length=20)),
                ('strategy_type', models.CharField(choices=[('SCALPING', 'Scalping'), ('SWING', 'Swing Trading'), ('DCA', 'Dollar Cost Averaging'), ('INTRADAY', 'Intraday Trading')], max_length=20)),
                ('gross_pnl', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, default='0.00', max_digits=15)),
                ('funding_fee', models.DecimalField(decimal_places=2, default='0.00', max_digits=15)),
                ('gas_fee', models.DecimalField(decimal_places=2, default='0.00', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
