# Generated by Django 4.2.16 on 2026-01-03 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='Biaya saat buka posisi', max_digits=15),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='entry_price',
            field=models.DecimalField(decimal_places=8, default='0.00', max_digits=20),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Waktu Open Posisi'),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='exit_fee',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='Biaya saat tutup posisi', max_digits=15),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='exit_price',
            field=models.DecimalField(decimal_places=8, default='0.00', max_digits=20),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='exit_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Waktu Close Posisi'),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='leverage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='notes',
            field=models.TextField(blank=True, help_text='Catatan analisa trading'),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='planned_rr',
            field=models.DecimalField(decimal_places=2, default='1.00', help_text='Target Risk-to-Reward', max_digits=5),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='position_size_usdt',
            field=models.DecimalField(decimal_places=2, default='0.00', help_text='Size dalam USDT (contoh: 100)', max_digits=20),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default='0.00', help_text='Jumlah koin (contoh: 0.0025)', max_digits=20),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='risk_amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=15),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='side',
            field=models.CharField(choices=[('LONG', 'Long Position'), ('SHORT', 'Short Position')], default='LONG', max_length=5),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='status',
            field=models.CharField(choices=[('WIN', 'Profit / Take Profit'), ('LOSS', 'Loss / Stop Loss'), ('BE', 'Break Even')], default='BE', max_length=10),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='tags',
            field=models.CharField(blank=True, help_text='Contoh: #FOMO #SesuaiPlan', max_length=100),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='strategy_type',
            field=models.CharField(blank=True, choices=[('SCALPING', 'Scalping'), ('INTRADAY', 'Intraday Trading'), ('SWING', 'Swing Trading'), ('POSITION', 'Position Trading')], max_length=20),
        ),
    ]
