# Generated by Django 5.2.9 on 2026-01-04 08:54

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_tradingaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradelog',
            name='commission',
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='asset_pair',
            field=models.CharField(help_text='Contoh: BTC/USDT', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='entry_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='exit_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='exit_price',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='exit_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='funding_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='gas_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='gross_pnl',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='planned_rr',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0000'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='position_size_usdt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), help_text='Margin yang digunakan', max_digits=20),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='risk_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='status',
            field=models.CharField(choices=[('WIN', 'Profit'), ('LOSS', 'Loss'), ('BE', 'Break Even')], default='BE', max_length=10),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='tags',
            field=models.CharField(blank=True, help_text='Contoh: #FOMO #Plan', max_length=100),
        ),
    ]
