# Generated by Django 4.2.16 on 2026-01-06 04:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_remove_tradelog_commission_alter_tradelog_asset_pair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradelog',
            name='entry_fee',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='exit_fee',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='funding_fee',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='gas_fee',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='gross_pnl',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='planned_rr',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='risk_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15),
        ),
    ]
